{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $style=''|soe_styles('header')
	 $classes=''|soe_classes('header')}
{if is_set($anchor_name)}<a name={$anchor_name} />{/if}
<a name="eztoc{$toc_anchor_name}" id="eztoc{$toc_anchor_name}"></a>
{switch name=sw match=$level}
{case match=1}
<h2 class="h1 {$classes|wash}"{if $style|ne('')} style="{$style}"{/if}>{$content}</h2>
{/case}
{case match=2}
<h3 class="h2 {$classes|wash}"{if $style|ne('')} style="{$style}"{/if}>{$content}</h3>
{/case}
{case match=3}
<h4 class="h3 {$classes|wash}"{if $style|ne('')} style="{$style}"{/if}>{$content}</h4>
{/case}
{case match=4}
<h5 class="h4 {$classes|wash}"{if $style|ne('')} style="{$style}"{/if}>{$content}</h5>
{/case}
{case match=5}
<h6 class="h5 {$classes|wash}"{if $style|ne('')} style="{$style}"{/if}>{$content}</h6>
{/case}
{case match=6}
<h6 class="{$classes|wash}"{if $style|ne('')} style="{$style}"{/if}>{$content}</h6>
{/case}
{case}
<h2 class="{$classes|wash}"{if $style|ne('')} style="{$style}"{/if}>{$content}</h2>
{/case}
{/switch}
