{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{section show=ne( $classification, 'html' )}
{def $style=''|soe_styles('literal')
	   $classes=''|soe_classes('literal')}
<pre{section show=ne($classes|trim,'')} class="{$classes|wash}"{/section}{if $style|trim|ne('')} style="{$style}"{/if}>{$content|wash(xhtml)}</pre>
{section-else}
{$content}
{/section}
