{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $style=''|soe_styles('ol')
	 $classes=''|soe_classes('ol')}
<ol{section show=ne($classes|trim,'')} class="{$classes|wash}"{/section}{if $style|trim|ne('')} style="{$style}"{/if}>
{$content}
</ol>
