{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $style=''|soe_styles('paragraph')
	$classes=''|soe_classes('paragraph')}
<p{if $classes|trim} class="{$classes|wash}"{/if}{if $style|trim} style="{$style}"{/if}>
{if eq( $content|trim(), '' )}&nbsp;{else}{$content}{/if}
</p>