{* DO NOT EDIT THIS FILE! Use an override template instead. 
*}{def $style=''|soe_styles('strike')
	   $classes=''|soe_classes('strike')}{*
*}<strike{if $classes|trim|ne('')} class="{$classes|wash}"{/if}{if $style|trim|ne('')} style="{$style}"{/if}>{$content}</strike>