{* DO NOT EDIT THIS FILE! Use an override template instead. 
*}{def $style=''|soe_styles('strong')
	   $classes=''|soe_classes('strong')}{*
*}<b{if $classes|trim|ne('')} class="{$classes|wash}"{/if}{if $style|trim|ne('')} style="{$style}"{/if}>{$content}</b>