{* DO NOT EDIT THIS FILE! Use an override template instead. 
*}{def $style=''|soe_styles('sub')
	   $classes=''|soe_classes('sub')}{*
*}<sub{if $classes|trim|ne('')} class="{$classes|wash}"{/if}{if $style|trim|ne('')} style="{$style}"{/if}>{$content}</sub>