{* DO NOT EDIT THIS FILE! Use an override template instead. 
*}{def $style=''|soe_styles('sup')
	   $classes=''|soe_classes('sup')}{*
*}<sup{if $classes|trim|ne('')} class="{$classes|wash}"{/if}{if $style|trim|ne('')} style="{$style}"{/if}>{$content}</sup>