{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default $classification=''}
{def $style=''}
{default $class_styles=ezini( 'sOExtraSettings', 'ClassStyles', 'soextra.ini',,true() )}{*
*}{if and( is_set($#use_inline_styles), $classification|trim, is_set($class_styles[$classification]) )}{*
	*}{set $style=concat($style, $class_styles[$classification]|wash) }{*
*}{/if}{*
*}{if and( is_set( $fontclass ), $fontclass|trim )}{*
	*}{if and( is_set($#use_inline_styles), is_set($class_styles[$fontclass]) ) }{*
		*}{set $style=concat($style, $class_styles[$fontclass]|wash) }{*
	*}{else}{*
		*}{set $classification = concat( $classification, ' ', $fontclass ) }{*
	*}{/if}{*
*}{/if}
{if and(is_set($forecolor), $forecolor|trim)}{set $style=concat($style, 'color:', $forecolor|wash, '; ') }{/if}
{if and(is_set($backcolor), $backcolor|trim)}{set $style=concat($style, 'background-color:', $backcolor|wash,'; ') }{/if}
{if and(is_set($fontsize), $fontsize|trim)}{if and( $fontsize|contains('px'), $fontsize|int|ge(10), $fontsize|int|le(26) )}{set $classification=concat( $classification, ' font-', $fontsize|wash )}{else}{set $style=concat($style, 'font-size:', $fontsize|wash, '; ') }{/if}{/if}
{if and(is_set($padding), $padding|trim)}{set $style=concat($style, 'padding:', $padding|wash, '; ') }{/if}
{if and(is_set($height), $height|trim)}{set $style=concat($style, 'height:', $height|wash, '; ') }{/if}
{if and(is_set($border), $border|trim)}{set $style=concat($style, 'border:', $border|wash, '; ') }{else}
{if and(is_set($border_color), $border_color|trim)}{set $style=concat($style, 'border-color:', $border_color|wash, '; ') }{/if}
{if and(is_set($border_style), $border_style|trim)}{set $style=concat($style, 'border-style:', $border_style|wash, '; ') }{/if}
{if and(is_set($border_size), $border_size|trim)}{set $style=concat($style, 'border-width:', $border_size|wash, '; ') }{/if}{/if}
{if and(is_unset($#use_inline_styles), is_unset($use_inline_styles))}
{if layout_line_start()|eq(true())}<div class="line">{/if}
<div class="unit size{$size}{if $last|eq('true')} lastUnit{/if}{if $classification|trim} {$classification|wash}{/if}"{if $style|ne('')} style="{$style}"{/if}>{$content}</div>
{if $last|eq('true')}{if layout_line_end()|eq(true)}</div>{/if}{/if}
{else}
{if layout_line_start()|eq(true())}<table border="0" cellpaddding="0" cellspacing="0" width="100%"><tr>{/if}
{def $width=""}
{if $last|ne('true')}
	{switch match=$size}
		{case match="1of2"}{set $width="50%"}{/case}
		{case match="1of3"}{set $width="33.333%"}{/case}
		{case match="2of3"}{set $width="66.666%"}{/case}
		{case match="1of4"}{set $width="25%"}{/case}
		{case match="2of4"}{set $width="50%"}{/case}
		{case match="3of4"}{set $width="75%"}{/case}
		{case match="1of5"}{set $width="20%"}{/case}
		{case match="2of5"}{set $width="40%"}{/case}
		{case match="3of5"}{set $width="60%"}{/case}
		{case match="4of5"}{set $width="80%"}{/case}
		{case}{/case}
	{/switch}
{/if}
<td width="{$width}" class="unit-table{if $last|eq('true')} lastUnit-table{/if}"{if $style|ne('')} style="{$style}"{/if} valign="top">{$content}</td>
{if $last|eq('true')}{if layout_line_end()|eq(true)}</tr></table>{/if}{/if}
{/if}