{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default $classification=''}
{def $style=''}
{default $class_styles=ezini( 'sOExtraSettings', 'ClassStyles', 'soextra.ini',,true() )}{*
*}{if and( is_set($#use_inline_styles), $classification|trim, is_set($class_styles[$classification]) )}{*
	*}{set $style=concat($style, $class_styles[$classification]|wash) }{*
*}{/if}{*
*}{if and( is_set( $fontclass ), $fontclass|trim )}{*
	*}{if and( is_set($#use_inline_styles), is_set($class_styles[$fontclass]) ) }{*
		*}{set $style=concat($style, $class_styles[$fontclass]|wash) }{*
	*}{else}{*
		*}{set $classification = concat( $classification, ' ', $fontclass ) }{*
	*}{/if}{*
*}{/if}
{if and(is_set($forecolor), $forecolor|trim)}{set $style=concat($style, 'color:', $forecolor|wash, '; ') }{/if}
{if and(is_set($backcolor), $backcolor|trim)}{set $style=concat($style, 'background-color:', $backcolor|wash,'; ') }{/if}
{if and(is_set($fontsize), $fontsize|trim)}{if and( $fontsize|contains('px'), $fontsize|int|ge(10), $fontsize|int|le(26) )}{set $classification=concat( $classification, ' font-', $fontsize|wash )}{else}{set $style=concat($style, 'font-size:', $fontsize|wash, '; ') }{/if}{/if}
{if and(is_set($padding), $padding|trim)}{set $style=concat($style, 'padding:', $padding|wash, '; ') }{/if}
{if and(is_set($height), $height|trim)}{set $style=concat($style, 'height:', $height|wash, '; ') }{/if}
{if and(is_set($width), $width|trim)}{set $style=concat($style, 'width:', $width|wash, '; ') }{/if}
{if and(is_set($border), $border|trim)}{set $style=concat($style, 'border:', $border|wash, '; ') }{else}
{if and(is_set($border_color), $border_color|trim)}{set $style=concat($style, 'border-color:', $border_color|wash, '; ') }{/if}
{if and(is_set($border_style), $border_style|trim)}{set $style=concat($style, 'border-style:', $border_style|wash, '; ') }{/if}
{if and(is_set($border_size), $border_size|trim)}{set $style=concat($style, 'border-width:', $border_size|wash, '; ') }{/if}{/if}
{column_count_inc(1)}{column_width_inc($width|int)}
<div class="col{if $classification|trim} {$classification|wash}{/if}"{if $style|ne('')} style="{$style}"{/if}>{$content}</div>