{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $style=''}
{default $class_styles=ezini( 'sOExtraSettings', 'ClassStyles', 'soextra.ini',,true() )}{*
*}{if and( or(is_set($#use_inline_styles), is_set($use_inline_styles)), $classification|trim, is_set($class_styles[$classification]) )}{*
	*}{set $style=concat($style, $class_styles[$classification]|wash) }{*
*}{/if}
{if and(is_set($padding), $padding)}{set $style=concat($style, 'padding:', $padding|wash, '; ') }{/if}
{if is_set($height)}{set $style=concat($style, 'height:', $height|wash, '; ') }{/if}
{if and(is_set($border), $border)}{set $style=concat($style, 'border:', $border|wash, '; ') }{else}
{if and(is_set($border_color), $border_color)}{set $style=concat($style, 'border-color:', $border_color|wash, '; ') }{/if}
{if and(is_set($border_style), $border_style)}{set $style=concat($style, 'border-style:', $border_style|wash, '; ') }{/if}
{if and(is_set($border_size), $border_size)}{set $style=concat($style, 'border-width:', $border_size|wash, '; ') }{/if}{/if}
<div class="object-{$object_parameters.align}{section show=ne($classification|trim,'')} {$classification|wash}{/section}"{section show=is_set($id)} id="{$id}"{/section}{if $style|ne('')} style="{$style}"{/if}>
{$object.name|wash} - {"You do not have permission to view this object"|i18n( 'design/admin/node/view/embed'  )}.
</div>