{* DO NOT EDIT THIS FILE! Use an override template instead. 
*}{def $embed_style=''
	   $css_class='content-view-embed-content'}{*
*}{default $class_styles=ezini( 'sOExtraSettings', 'ClassStyles', 'soextra.ini',,true() )}{*
*}{if and( or(is_set($#use_inline_styles), is_set($use_inline_styles)), $classification|trim, is_set($class_styles[$classification]) )}{*
	*}{set $embed_style=concat($embed_style, $class_styles[$classification]|wash) }{*
*}{/if}{*
*}{if and( is_set( $fontclass ), $fontclass|trim )}{*
	*}{if and( or(is_set($#use_inline_styles), is_set($use_inline_styles)), is_set($class_styles[$fontclass]) ) }{*
		*}{set $embed_style=concat($embed_style, $class_styles[$fontclass]|wash) }{*
	*}{else}{*
		*}{set $classification = concat( $classification, ' ', $fontclass ) }{*
	*}{/if}{*
*}{/if}{*
*}{if or(is_set($#use_inline_styles), is_set($use_inline_styles))}{*
	*}{set $embed_style=concat($embed_style, cond($object_parameters.align|eq('right'), 'clear:right;float:right;', 'clear:left;float:left;') ) }{*
*}{else}{*
	*}{set $css_class=concat( $css_class, cond( $object_parameters.align, concat(' object-',$object_parameters.align), '' ) ) }{*
*}{/if}{*
*}{if and(is_set($margin), $margin|trim)}{set $embed_style=concat($embed_style, 'margin:', $margin|wash, '; ') }{set $margin=''}{/if}{*
*}{if and(is_set($padding), $padding|trim)}{set $embed_style=concat($embed_style, 'padding:', $padding|wash, '; ') }{set $padding=''}{/if}{*
*}{if and(is_set($border), $border|trim)}{set $embed_style=concat($embed_style, 'border:', $border|wash, '; ') }{set $border=''}{else}{*
*}{if and(is_set($border_color), $border_color|trim)}{set $embed_style=concat($embed_style, 'border-color:', $border_color|wash, '; ') }{set $border_color=''}{/if}{*
*}{if and(is_set($border_style), $border_style|trim)}{set $embed_style=concat($embed_style, 'border-style:', $border_style|wash, '; ') }{set $border_style=''}{/if}{*
*}{if and(is_set($border_size), $border_size|trim)}{set $embed_style=concat($embed_style, 'border-width:', $border_size|wash, '; ') }{set $border_size=''}{/if}{/if}{node_view_gui view=$view link_parameters=$link_parameters object_parameters=$object_parameters content_node=$node object=$object classification=$classification in_oe=cond(is_set($in_oe),true()) inner_style=$embed_style css_class=cond($css_class, $css_class)}