{* DO NOT EDIT THIS FILE! Use an override template instead.
*}{def $style=''|soe_styles('embed-inline')
	 $classes='content-view-embed-content '|soe_classes('embed-inline')}{*
*}{content_view_gui view=$view link_parameters=$link_parameters object_parameters=$object_parameters content_object=$object classification=$classification in_oe=cond(is_set($in_oe),true()) inline=true() inner_style=$style css_class=cond($classes, $classes)}