{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $style=''}
{if and(is_set( $align ), $align|trim )}{if and(is_unset($#use_inline_styles), is_unset($use_inline_styles))}{set $classification=concat( $classification, ' text-', $align )}{else}{set $style=concat('text-align:',$align,'; ')}{/if}{/if}
{default $class_styles=ezini( 'sOExtraSettings', 'ClassStyles', 'soextra.ini',,true() )}{*
*}{if and( or(is_set($#use_inline_styles), is_set($use_inline_styles)), $classification|trim, is_set($class_styles[$classification]) )}{*
	*}{set $style=concat($style, $class_styles[$classification]|wash) }{*
*}{/if}{*
*}{if and( is_set( $fontclass ), $fontclass|trim )}{*
	*}{if and( or(is_set($#use_inline_styles), is_set($use_inline_styles)), is_set($class_styles[$fontclass]) ) }{*
		*}{set $style=concat($style, $class_styles[$fontclass]|wash) }{*
	*}{else}{*
		*}{set $classification = concat( $classification, ' ', $fontclass ) }{*
	*}{/if}{*
*}{/if}
{if and(is_set($forecolor), $forecolor|trim)}{set $style=concat($style, 'color:', $forecolor|wash, '; ') }{/if}
{if and(is_set($backcolor), $backcolor|trim)}{set $style=concat($style, 'background-color:', $backcolor|wash,'; ') }{/if}
{if and(is_set($fontsize), $fontsize|trim)}{if and( and(is_unset($#use_inline_styles), is_unset($use_inline_styles)), $fontsize|contains('px'), $fontsize|int|ge(10), $fontsize|int|le(26) )}{set $classification=concat( $classification, ' font-', $fontsize|wash )}{else}{set $style=concat($style, 'font-size:', $fontsize|wash, '; ') }{/if}{/if}
{if and(is_set($lineheight), $lineheight|trim)}{set $style=concat($style, 'line-height:', $lineheight|wash, '; ') }{/if}
{if and(is_set($margin), $margin|trim)}{set $style=concat($style, 'margin:', $margin|wash, '; ') }{/if}
{if and(is_set($padding), $padding|trim)}{set $style=concat($style, 'padding:', $padding|wash, '; ') }{/if}
{if and(is_set($width), $width|trim)}{set $style=concat($style, 'width:', $width|wash, '; ') }{/if}
{if and(is_set($border), $border|trim)}{set $style=concat($style, 'border:', $border|wash, '; ') }{else}
{if and(is_set($border_color), $border_color|trim)}{set $style=concat($style, 'border-color:', $border_color|wash, '; ') }{/if}
{if and(is_set($border_style), $border_style|trim)}{set $style=concat($style, 'border-style:', $border_style|wash, '; ') }{/if}
{if and(is_set($border_size), $border_size|trim)}{set $style=concat($style, 'border-width:', $border_size|wash, '; ') }{/if}{/if}
{if is_set($anchor_name)}<a name={$anchor_name} />{/if}
<a name="eztoc{$toc_anchor_name}" id="eztoc{$toc_anchor_name}"></a>
{switch name=sw match=$level}
{case match=1}
<h1{if $classification|trim} class="{$classification|wash}"{/if}{if $style|ne('')} style="{$style}"{/if}>{$content}</h1>
{/case}
{case match=2}
<h2{if $classification|trim} class="{$classification|wash}"{/if}{if $style|ne('')} style="{$style}"{/if}>{$content}</h2>
{/case}
{case match=3}
<h3{if $classification|trim} class="{$classification|wash}"{/if}{if $style|ne('')} style="{$style}"{/if}>{$content}</h3>
{/case}
{case match=4}
<h4{if $classification|trim} class="{$classification|wash}"{/if}{if $style|ne('')} style="{$style}"{/if}>{$content}</h4>
{/case}
{case match=5}
<h5{if $classification|trim} class="{$classification|wash}"{/if}{if $style|ne('')} style="{$style}"{/if}>{$content}</h5>
{/case}
{case match=6}
<h6{if $classification|trim} class="{$classification|wash}"{/if}{if $style|ne('')} style="{$style}"{/if}>{$content}</h6>
{/case}
{case}
<h2{if $classification|trim} class="{$classification|wash}"{/if}{if $style|ne('')} style="{$style}"{/if}>{$content}</h2>
{/case}
{/switch}
