{* DO NOT EDIT THIS FILE! Use an override template instead. 
*}{def $style=''|soe_styles('li')
	   $classes=''|soe_classes('li')}{*
*}<li{if $classes|trim|ne('')} class="{$classes|wash}"{/if}{if $style|trim|ne('')} style="{$style}"{/if}>{$content}</li>