{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $style=''|soe_styles('separator')
	$classes=''|soe_classes('separator')}
<div class="separator{if $classes|trim|ne('')} {$classes|wash}"{/if}"{if $style|trim|ne('')} style="{$style}"{/if}>
    <div class="separator-design"></div>
</div>