{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $style=''|soe_styles('td')
     $classes=''|soe_classes('td')}
<td{if $classes|trim|ne('')} class="{$classes|wash}"{/if}{if $colspan} colspan="{$colspan}"{/if}{if $rowspan} rowspan="{$rowspan}"{/if}{if $width} width="{$width}"{/if}{if and(is_set( $scope ), $scope)} scope="{$scope|wash}"{/if}{if and(is_set( $abbr ), $abbr)} abbr="{$abbr|wash}"{/if} valign="{first_set( $valign, 'top')}"{if $style|trim|ne('')} style="{$style}"{/if}>
{switch name=Sw match=$content}
  {case match="<p></p>"}
  &nbsp;
  {/case}
  {case match=""}
  &nbsp;
  {/case}
  {case}
  {$content}
  {/case}
{/switch}
</td>